# Generated by Django 4.2.4 on 2023-11-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LuxuryOption',
        ),
    ]
