# Generated by Django 4.2.4 on 2023-11-19 09:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Custom Client',
                'verbose_name_plural': 'Custom Clients',
            },
        ),
    ]
