# Generated by Django 4.2.4 on 2023-11-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_customclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customclient',
            name='name',
        ),
        migrations.AddField(
            model_name='customclient',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customclient',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
