# Generated by Django 4.2.4 on 2023-11-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_delete_customclient_reservation_citizenship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='occupied_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
