# Generated by Django 4.2.4 on 2023-11-19 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_room_occupied_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='type',
        ),
        migrations.RemoveField(
            model_name='room',
            name='occupied_type',
        ),
    ]
