# Generated by Django 4.2.4 on 2023-11-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_alter_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='people',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
