# Generated by Django 4.2.4 on 2024-01-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_reservation_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Luxury',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='luxuries',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
