# Generated by Django 4.2.4 on 2024-01-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_alter_luxury_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='luxury',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
