# Generated by Django 4.2.4 on 2024-01-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_luxury_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='luxuries',
        ),
        migrations.AddField(
            model_name='room',
            name='luxuries',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='hotel.luxury'),
        ),
    ]
