# Generated by Django 4.2.4 on 2024-01-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_remove_room_luxuries_room_luxuries'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reserved_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='luxuries',
            field=models.ManyToManyField(to='hotel.luxury'),
        ),
    ]
