# Generated by Django 4.2.4 on 2024-01-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_reservation_reserved_on_alter_room_luxuries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luxury',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
