# Generated by Django 4.2.4 on 2024-01-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0019_remove_hotel_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='short_code',
            field=models.CharField(blank=True, default='7a051d16', max_length=100, null=True),
        ),
    ]
