# Generated by Django 4.2.4 on 2024-01-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0020_hotel_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='short_code',
            field=models.CharField(blank=True, default='de6a7ee7', max_length=100, null=True, unique=True),
        ),
    ]
