# Generated by Django 4.2.4 on 2024-01-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0022_remove_hotel_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='short_code',
            field=models.CharField(blank=True, default='af4e6e98', max_length=100, null=True, unique=True),
        ),
    ]
