# Generated by Django 4.2.4 on 2024-01-22 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0023_hotel_short_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='short_code',
        ),
    ]
