# Generated by Django 4.2.4 on 2024-02-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0024_remove_hotel_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='photos',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
