# Generated by Django 4.2.4 on 2023-11-17 12:18

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hotel', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('banned', models.BooleanField(blank=True, default=False, null=True)),
                ('confirmedusername', models.BooleanField(blank=True, default=False, null=True)),
                ('confirmedemail', models.BooleanField(blank=True, default=False, null=True)),
                ('confirmedname', models.BooleanField(blank=True, default=False, null=True)),
                ('confirmedrole', models.BooleanField(blank=True, default=False, null=True)),
                ('confirmedcitizenship', models.BooleanField(blank=True, default=False, null=True)),
                ('confirmedphone', models.BooleanField(blank=True, default=False, null=True)),
                ('verifiedemail', models.BooleanField(blank=True, default=False, null=True)),
                ('welcome_email_sent', models.BooleanField(blank=True, default=False, null=True)),
                ('two_fa_enabled', models.BooleanField(blank=True, default=False, null=True)),
                ('factor', models.CharField(blank=True, max_length=120, null=True)),
                ('factor_passed', models.BooleanField(blank=True, default=False, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('citizenship', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('role', models.CharField(blank=True, choices=[('user', 'User'), ('hotel_manager', 'Manager'), ('employee', 'Employee'), ('admin', 'Admin')], max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('hotel', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel', to='hotel.hotel')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
