# Generated by Django 4.2.4 on 2023-08-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('manager', 'Manager'), ('employee', 'Employee'), ('admin', 'Admin')], max_length=20, null=True),
        ),
    ]
