# Generated by Django 4.2.4 on 2023-08-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_confirmedemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmedname',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='confirmedrole',
            field=models.BooleanField(default=False),
        ),
    ]
