# Generated by Django 4.2.4 on 2023-08-07 05:14

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_confirmedname_customuser_confirmedrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='citizenship',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='confirmedcitizneship',
            field=models.BooleanField(default=False),
        ),
    ]
