# Generated by Django 4.2.4 on 2023-08-07 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_citizenship_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='confirmedcitizneship',
            new_name='confirmedcitizenship',
        ),
    ]
