# Generated by Django 4.2.4 on 2023-08-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_confirmedcitizneship_customuser_confirmedcitizenship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmedcitizenship',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
