# Generated by Django 4.2.4 on 2023-08-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_customuser_confirmedcitizenship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmedemail',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='confirmedname',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='confirmedrole',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='confirmedusername',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
