# Generated by Django 4.2.4 on 2023-08-07 05:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_customuser_confirmedemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmedphone',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
