# Generated by Django 4.2.4 on 2023-08-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_customuser_confirmedphone_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='banned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
